### ISSUE TITLE
updating notion-linux.list

### ISSUE THREAD

**Issue by niniack** [davidbailey00/notion-linux#29]
Hey, 

When attempting to install from the ubuntu repository, `sudo apt update` would ignore the repository. 

I had to make the following change in `notion-linux.list`: 

`deb [trusted=yes] https://notion.davidbailey.codes/debs/ stable main`

to 

`deb [arch=amd64, trusted=yes] https://notion.davidbailey.codes/debs/ stable main`

Not sure what the most flexible/universal way of tackling this issue is but I wanted to raise this in case others are having this problem!

**Comment by vtenfys** [comment]
Thanks for the report, can you post what happens when you `apt update` without this change? Possibly related to #26 

I'm not sure the suggested line would work for everyone seeing as the repo also provides `arm64` packages. Also, I haven't had to make this change during my own testing (in Ubuntu on WSL) for the repo to work.

**Comment by niniack** [comment]
The relevant error after running `apt update` is
```
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://notion.davidbailey.codes/debs stable InRelease' doesn't support architecture 'i386'
```
It does look like it is related to the issue you tagged!

I'd be curious to know what a universal way of solving this would be! Thanks for helping out :)

**Comment by vtenfys** [comment]
Thanks! I don't think this is anything more than an informational message, so you should still be able to install the package without changing the repository line - can you check if doing so works with the original line?

It might be possible to have the following to stub the message and remain compatible with arm64:

```
deb [arch=amd64,arm64, trusted=yes] https://notion.davidbailey.codes/debs/ stable main
```

although I'm not sure if this would cause issues given that the two architectures are incompatible with each other. I'll just test it in my arm64 Parallels VM to see if it works okay. cc @magikid

**Comment by vtenfys** [comment]
The line in my last message seems to only fetch contents for amd64 when running on arm64, so that's not a workable solution. Splitting into multiple lines, ie:

```
deb [arch=amd64 trusted=yes] https://notion.davidbailey.codes/debs/ stable main
deb [arch=arm64 trusted=yes] https://notion.davidbailey.codes/debs/ stable main
```

causes a set of warnings to appear about duplicate content, so that doesn't work either.

I could instruct people to download a different list file based on architecture, but I think it might be overcomplicating things given the message from Apt is only informational and shouldn't prevent installation. Instead it might be better to clarify the reasoning behind the message (i.e. multiarch systems) in the README so people don't worry about it - thoughts on that?

And I could also point people to this issue so they can change the line themselves if they want to stub the message.

**Comment by niniack** [comment]
> Thanks! I don't think this is anything more than an informational message, so you should still be able to install the package without changing the repository line - can you check if doing so works with the original line?
> 
> It might be possible to have the following to stub the message and remain compatible with arm64:
> 
> ```
> deb [arch=amd64,arm64, trusted=yes] https://notion.davidbailey.codes/debs/ stable main
> ```
> 
> although I'm not sure if this would cause issues given that the two architectures are incompatible with each other. I'll just test it in my arm64 Parallels VM to see if it works okay. cc @magikid

Yeah whoops, seems like I can go ahead and install it by ignoring the warning message. My bad! Should've tested it out before raising an issue, that too a duplicated one 😬

Also, I think linking to the issue(s) somehow, maybe in the README, could help avoid potential confusion for those worried about the warning! Edit: I agree that different instructions per architecture is overkill

Thanks for your patience :)

**Comment by vtenfys** [comment]
> Also, I think linking to the issue(s) somehow, maybe in the README, could help avoid potential confusion for those worried about the warning! Edit: I agree that different instructions per architecture is overkill

I've now added info on this to the README, so closing.

> Yeah whoops, seems like I can go ahead and install it by ignoring the warning message. My bad! Should've tested it out before raising an issue, that too a duplicated one 😬

No need to apologise, it seems like something I should address properly seeing as a number of people spotted it :)
