### ISSUE TITLE
[Feature Request] Backward and Forward buttons and shortcuts

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [davidbailey00/notion-linux#32]
I would like to request a way to go to the previous page and forward page. Basically what the browser allows me to do.

Two buttons on the top menu and the respective keyboard and mouse shortcuts would be ideal.

Thank you for your attention.

**Comment by vtenfys** [comment]
Hi and thanks for opening this issue!

First of all, the goal of this project is only to port the Windows build of Notion Desktop to Linux, and not implement additional features. If you want to install a build of Notion with additional features then please use the `notion-enhanced` package, which includes the [Notion Enhancer](https://github.com/notion-enhancer/notion-enhancer) modpack.

Secondly, I believe the feature you are looking for is already available in the unmodified Notion build (`notion-desktop`), as you can see in the screenshot below:

![image](https://user-images.githubusercontent.com/4248177/108381269-8d878480-71ff-11eb-81c2-150a0a209c72.png)

Shortcuts to go back and forward are <kbd>Ctrl+[</kbd> and <kbd>Ctrl+]</kbd> respectively.

Please let me know if this doesn't solve your issue!

**Comment by RicardoEPRodrigues** [comment]
Hey, my bad. I did miss that. I tried it with a mouse and it works just fine.

But, when I use a touchpad it does not work as intended. Perhaps this is not something you want to implement, as it might be an edge-case, but here it is.

On my laptop, I use Wayland and GNOME, along with [an extension that lets me define touchpad gestures](https://github.com/mpiannucci/gnome-shell-extended-gestures). With this extension, I am able to define horizontal three-finger swipes to go backward and forward. These gestures work fine in Firefox and many other applications, but not on this one.

On this app, when I swipe, it goes from the Notion view to the top menu, if I swipe again it goes back.

The extension claims it uses `libinput` to determine the swipes. Hope this explanation helps.

**Comment by vtenfys** [comment]
Thanks, I had a look at the code for the extension you linked and found the reason it does not work:

https://github.com/mpiannucci/gnome-shell-extended-gestures/blob/v6/extendedgestures@mpiannucci.github.com/extension.js#L180-L185

The back/forward events are hardcoded to the keyboard shortcuts <kbd>Alt+Left</kbd> and <kbd>Alt+Right</kbd> rather than being generic - therefore I consider this to be a problem with the extension.

You have a few options:

1. Ask the maintainer of this extension to implement this differently (I'm not familiar with GNOME Shell extension development but I think it might be possible to send generic 'back' and 'forward' events rather than hardcoding keyboard shortcuts)
2. Find a different extension that allows binding a touchpad gesture to a custom keyboard shortcut
3. [Open a feature proposal in Notion Enhancer](https://github.com/notion-enhancer/notion-enhancer/issues/new?assignees=&labels=enhancement&template=feature-proposal.md&title=) to request keyboard shortcut remapping or similar - if a feature of such makes it into Notion Enhancer then it would subsequently become available in the `notion-enhanced` package

Since this would be an additional feature, it is out of the scope of this project.

**Comment by RicardoEPRodrigues** [comment]
Thank you for the time spent on this. I'll try to reach out to the developer.
