### ISSUE TITLE
Not on debian, Fedora or openSUSE, how to install

### ISSUE THREAD

**Issue by lf-araujo** [davidbailey00/notion-linux#35]
Thanks for this great software.

When I was on Ubuntu, this worked swiftly. However I migrated to solus some months ago and I wonder:

- Are there instructions to generate generic binaries, appimages or snap packages for this?

**Comment by vtenfys** [comment]
For generic Linux binaries, you can do the following:

1. run `build.sh` but skip `package-[TYPE].sh`
2. copy the directory `"build/build-[NOTION VERSION]-[REVISION]-[ARCHITECTURE]/notion-desktop-linux-[ARCHITECTURE]` into a location of your choice
3. use the `notion-desktop` binary inside that directory to launch Notion (you could create your own `.desktop` entry for this if you like)

Unfortunately this won't work for `notion-enhanced` due to the way it loads modules from a hardcoded directory - you can have a look at notion-enhancer/notion-enhancer/issues/321 to see progress on that front.

For Snap, you can use [notion-snap](https://snapcraft.io/notion-snap) - this isn't maintained by me and doesn't include Notion Enhancer mods, so I cannot provide assistance, but if you don't care about enhancements then this should be fine.

I'm not aware of any AppImage versions and not sure how to do this off the top of my head, but this could be possible if enough people are interested - however it seems most people are using Ubuntu so I'm not sure if I will implement this in the short term.

Hope that helps :)

**Comment by vtenfys** [comment]
Actually, for `notion-enhanced`, if you modify [this line](https://github.com/davidbailey00/notion-linux/blob/5ac066b/scripts/enhance.sh#L61) of `enhance.sh` so that it points to wherever you plan to put the `notion-enhanced-linux-[ARCHITECTURE]` directory, then it should hopefully work - so the full steps would be:

1. run `build.sh`
2. modify that line of `enhance.sh` so that `/usr/lib/notion-enhanced` instead points to **X**
2. run `enhance.sh`
2. copy the directory `"build/build-[NOTION VERSION]-[REVISION]-[ARCHITECTURE]/notion-enhanced-linux-[ARCHITECTURE]` into a location of your choice (**X**)
3. use the `notion-enhanced` binary inside that directory to launch Notion

**Comment by lf-araujo** [comment]
This is already more than enough help, thank you so much! Will try these instructions.

**Comment by lf-araujo** [comment]
Just some feedback, your instructions are totally correct. Worked first time. Thanks.

**Comment by vtenfys** [comment]
Happy to hear :)
