### ISSUE TITLE
Is this really necessary? 

### ISSUE THREAD

**Issue by cemetary** [davidbailey00/notion-linux#37]
Since Notion is only offered in English and Korean, what's the point of this?

![Screenshot from 2021-03-01 17 07 25](https://user-images.githubusercontent.com/10538213/109571291-5f4d5300-7ae3-11eb-931a-3c448d5639df.png)

**Comment by vtenfys** [comment]
This is a bug with apt when using ["trivial archive" repositories](https://wiki.debian.org/DebianRepository/Setup#Debian_Repository_Types) rather than the "official archive" format - `Ign` stands for "ignore" since these files don't exist, but apt tries to download them anyway and logs the same lines multiple times.

The repository format is outside of my control since I'm using [Gemfury](https://gemfury.com) which manages the repository for me - previously I was managing the repository myself and hosting with Firebase, but the bandwidth was too expensive.

I'm closing this since it's outside of my control, and these lines can be safely ignored.

**Comment by cemetary** [comment]
Oh, now I see. Thanks for your response.
